config/routes.rb
Rails.application.routes.draw do

# 顧客用
# URL /uers/sign_in ...
devise_for :users, skip:[:passwords], controllers:{
  registrations: "public/registrations",
  sessions: "public/sessions"
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip:[:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

# ゲストログイン用
devise_scope :user do
  post 'public/guest_sign_in', to: 'public/sessions#guest_sign_in'
end

namespace :admin do
  resources :shifts, only: [:index, :edit, :update]
  resources :users, only: [:index]
end

scope module: :public do
  root 'homes#top'
  get 'inquiry/index' => 'inquiry#index' # 入力画面
  post 'inquiry/confirm' => 'inquiry#confirm' # 確認画面
  post 'inquiry/thanks'  => 'inquiry#thanks' # 送信完了画面
  get 'users/unsubscribe' => 'users#unsubscribe', as: 'confirm_unsubscribe'
  patch 'users/withdraw' => 'users#withdraw', as: 'withdraw_user'
  put 'users/withdraw' => 'users#withdraw'
  get '/about' => 'homes#about'
  resources :shifts, only: [:index, :create, :edit, :update, :destroy]
end


end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | SimplyShiftApp

    = csrf_meta_tags
    = csp_meta_tag
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    link[rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css"]
    link[rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome-animation/0.0.10/font-awesome-animation.css" type="text/css" media="all"]

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    div.footerFixed
      header.border-bottom.sticky-top
        .nav.navbar.navbar-expand-lg.navbar-dark.bg-light
          .container
            .navbar-brand.faa-parent.animated-hover
              = link_to 'SimplyShift', root_path, class:"logo text-dark fas fa-calendar-alt faa-float"

            button.navbar-toggler[type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation"]
              span.navbar-toggler-icon

          #navbarNavDropdown.collapse.navbar-collapse
            ul.navbar-nav.ml-auto

              - if admin_signed_in?
                li.nav-item.border.rounded-lg.text-nowrap.faa-parent.animated-hover
                   = link_to " シフト一覧", admin_shifts_path, class: 'nav-link text-dark far fa-calendar-check faa-bounce'
                li.nav-item.border.rounded-lg.text-nowrap.faa-parent.animated-hover
                  = link_to " 社員一覧", admin_users_path, class: 'nav-link text-dark far fa-user faa-bounce'
                li.nav-item.border.rounded-lg.text-nowrap.faa-parent.animated-hover
                  = link_to " ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark far fa-arrow-alt-circle-right faa-bounce'
                li.nav-item.border.rounded-lg.text-nowrap.faa-parent.animated-hover
                  = link_to " お問合せ", inquiry_index_path, class: 'nav-link text-dark far fa-paper-plane faa-bounce'
              - elsif user_signed_in?
                li.nav-item.border.rounded-lg.text-nowrap.faa-parent.animated-hover
                  = link_to " シフト登録", shifts_path, class: 'nav-link text-dark far fa-calendar-plus faa-bounce'
                li.nav-item.border.rounded-lg.text-nowrap.faa-parent.animated-hover
                  = link_to " ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark far fa-arrow-alt-circle-right faa-bounce'
                li.nav-item.border.rounded-lg.text-nowrap.faa-parent.animated-hover
                  = link_to " 退会確認", confirm_unsubscribe_path, class: 'nav-link text-dark far fa-window-close faa-bounce'
                li.nav-item.border.rounded-lg.text-nowrap.faa-parent.animated-hover
                  = link_to " お問合せ", inquiry_index_path, class: 'nav-link text-dark far fa-paper-plane faa-bounce'
              - else
                li.nav-item.border.rounded-lg.text-nowrap.faa-parent.animated-hover
                  = link_to " お問合せ", inquiry_index_path, class: 'nav-link text-dark far fa-paper-plane faa-bounce'

      main
        == yield

      footer.fixed-bottom.border-top.bg-light
        .container.mt-5
          .row.justify-content-center
              | Copyright ©️ 2021 ShotaroAkaishi All Rights Reserved.